### ISSUE TITLE
Feature request & 404 errors from static.computer-vision-talks.com

### ISSUE THREAD

**Issue by danrubins** [BloodAxe/npm-native-opencv#1]
First off, great work on this and your CV Talks - they have been really helpful.

Feature request: it would be great if the cdn link could be swapped out.
The more pressing issue right now is the 404 errors for everything from http://static.computer-vision-talks.com/dist/opencv/:

```
/home/rof/src/github.com/dhrubins/LegalRobot-App/packages/npm-container/.npm/package-new-15ygtl1/node_modules/native-opencv/installer.js:69
throw err;
^
Error: Couldn't connect to
http://static.computer-vision-talks.com/dist/opencv/opencv-3.0.0b-unix.zip
(404)
at Download.res
```

**Comment by BloodAxe** [comment]
Hey! Sorry, it was my fault. I was migrating blog to new host. While updating DNS records I accidentally changed IP address of static.computer-vision-talks.com. Now it's back to normal, so try re-running install. 
If the problem persists, give it few hours to replicate DNS update. If it's still exists - feel free to reopen issue.

**Comment by danrubins** [comment]
Thanks for the quick follow up - looks good now.

**Comment by BloodAxe** [comment]
@dhrubins good to know! Can you suggest nice CDN to host those binaries?

**Comment by danrubins** [comment]
I think AWS will give you a generous allowance in their free tier (first year only), and it's pretty cheap after that. Other CDNs have pretty permissive bandwidth charges - I've had good results with MaxCDN. But, if you don't have huge traffic and want something a bit less formal, you could try rawgit.com. I haven't tried it for my stuff, but I've noticed a couple things I use are served from rawgit.
